### ISSUE TITLE
[Feature request] Add support for multiple server urls in the settings field

### ISSUE THREAD

**Issue by PencilNotPen** [alextud/PopcornTimeTV#13]
Hi Alextud, thanks again for this great app!

I was wondering if it would be possible to add support for multiple server urls in the settings field? The app would then cycle through them to find the fastest or first one up. This would provide redundancy if one server goes down. The picture shows the feature in the macOS version:

![example](https://github.com/alextud/PopcornTimeTV/assets/20209529/b5e3b0d4-ded9-49a2-8ae7-dfdc6817c1eb)

Unfortunately, I doubt you have access to the code which allows the 'automatically update API server urls' feature(?). However, would it be possible to as a lesser solution, allow multiple urls to be entered in the Popcorn url field, separated by a , as shown in the attached image?

No worries if not, and thanks again for your great work on this app. Cheers!

**Comment by alextud** [comment]
I've added support for a string with multiple urls. But also it should get those urls from DHT node (torrent).
