### ISSUE TITLE
Doesn't compile on Xcode 14.3 (14E222b)

### ISSUE THREAD

**Issue by PencilNotPen** [alextud/PopcornTimeTV#5]
App version: tvOS, macOS, current commit of PopcornTimeTV at time of posting issue.

The app fails to build on tvOS and macOS (iOS not tested) on Xcode 14.3. Works on Xcode 14.2.

Error:

Kingfisher:KFImageRenderer: Initializer for conditional binding must have Optional type, not 'AnyView'

Suggests the following code section in relation to the above message:

if let placeholder = context.placeholder, let view = placeholder(binder.progress) {

Many thanks for your great work on this app, it is incredible on Apple TV, and much appreciated!

**Comment by fancyham** [comment]
Solution: 
You need to pull in a more recent version of Kingfisher.  To do this: in Xcode's left sidebar > Package Dependencies > Kingfisher, right-click and choose 'Update'. 

The problem seemed to be that the version of Kingfisher pulled in by this repo was 7.5 (or something similar) which is outdated.  After the update, I was able to compile successfully.
